## Emscripten support, Memory64, string interning, and additional CLI flags.
## Provides emscripten-compatible JS glue generation, 64-bit pointer support,
## string caching, and wasm binary post-processing flags.

import std/strutils
import std/strformat
import std/tables

import common
import leb128

# ─── Emscripten Output Mode ───

type
  EmscriptenConfig* = object
    addToLibrary*: bool
    globalDeps*: seq[string]
    importDeps*: seq[string]
    libraryVars*: seq[(string, string)]

proc escapeJsString(s: string): string =
  result = ""
  for c in s:
    case c
    of '\\': result.add("\\\\")
    of '"': result.add("\\\"")
    of '\n': result.add("\\n")
    of '\r': result.add("\\r")
    of '\t': result.add("\\t")
    else: result.add(c)

proc generateEmscriptenJs*(prog: Program, config: EmscriptenConfig): string =
  ## Generate emscripten-compatible JS glue code.
  ## Uses addToLibrary format instead of ES module exports.
  result = ""
  result.add("// Auto-generated by nimbling (emscripten target)\n")
  result.add("// Emscripten JS library file\n\n")

  # Library variables
  for (key, val) in config.libraryVars:
    result.add(&"var {key} = {val};\n")
  if config.libraryVars.len > 0:
    result.add("\n")

  # Global dependencies
  if config.globalDeps.len > 0:
    result.add("// Global dependencies\n")
    for dep in config.globalDeps:
      result.add(&"// @dep: {dep}\n")
    result.add("\n")

  # Import dependencies
  if config.importDeps.len > 0:
    result.add("// Import dependencies\n")
    for dep in config.importDeps:
      result.add(&"// @import: {dep}\n")
    result.add("\n")

  # Generate export wrappers
  for exp in prog.exports:
    let f = exp.function
    let jsName = f.name

    if config.addToLibrary:
      result.add(&"var {NbgPrefix}{jsName} = ")
    else:
      result.add(&"function {NbgPrefix}{jsName}(")

    # Arguments
    var argNames: seq[string] = @[]
    for i, arg in f.args:
      argNames.add(&"arg{i}")

    if not config.addToLibrary:
      result.add(argNames.join(", "))
      result.add(") {\n")
    else:
      result.add("function(" & argNames.join(", ") & ") {\n")

    # Body
    if f.args.len > 0:
      result.add(&"  // args: {f.args.len}\n")

    let retStr = if f.retTyOverride.len > 0: f.retTyOverride else: "void"
    result.add(&"  // returns: {retStr}\n")

    if config.addToLibrary:
      result.add("};\n")
    else:
      result.add("}\n")
    result.add("\n")

  # Export functions from wasm
  for exp in prog.exports:
    let f = exp.function
    if exp.class.isNone:
      result.add(&"// export: {f.name}\n")

  # Generate struct class wrappers for emscripten
  for s in prog.structs:
    let className = s.name
    result.add(&"// class: {className}\n")
    result.add(&"var {NbgPrefix}{className.toLowerAscii()}_new = function() {{\n")
    result.add(&"  return _{NbgPrefix}{className.toLowerAscii()}_new();\n")
    result.add("};\n\n")

    result.add(&"var {NbgPrefix}{className.toLowerAscii()}_free = function(ptr) {{\n")
    result.add(&"  _{NbgPrefix}{className.toLowerAscii()}_free(ptr);\n")
    result.add("};\n\n")

  # Imports section
  for imp in prog.imports:
    case imp.importKind.kind
    of ikFunction:
      let f = imp.importKind.funcData.function
      result.add(&"// import: {f.name}\n")
    of ikType:
      let t = imp.importKind.typeData
      result.add(&"// import type: {t.name}\n")
    else:
      discard

# ─── Memory64 Support ───

type
  Memory64Config* = object
    enabled*: bool
    pointerSize*: int

proc coercePtrSuffix*(config: Memory64Config): string =
  ## Returns ">>> 0" for wasm32, "" for wasm64.
  if config.enabled and config.pointerSize == 64:
    return ""
  return " >>> 0"

proc coercePtrAssign*(config: Memory64Config): string =
  ## Returns pointer coercion for assignment.
  if config.enabled and config.pointerSize == 64:
    return ""
  return " >>> 0"

proc memoryType*(config: Memory64Config): string =
  ## Returns the wasm memory type string.
  if config.enabled and config.pointerSize == 64:
    return "i64"
  return "i32"

proc ptrLoadOp*(config: Memory64Config): string =
  ## Returns the appropriate load opcode name.
  if config.enabled and config.pointerSize == 64:
    return "i64.load"
  return "i32.load"

proc ptrStoreOp*(config: Memory64Config): string =
  ## Returns the appropriate store opcode name.
  if config.enabled and config.pointerSize == 64:
    return "i64.store"
  return "i32.store"

proc ptrConstJs*(config: Memory64Config, value: uint64): string =
  ## Format a pointer constant in JS.
  if config.enabled and config.pointerSize == 64:
    return $value & "n"
  return $value

proc generateMemory64Coercion*(config: Memory64Config, expr: string): string =
  ## Wrap an expression with pointer coercion if needed for wasm32.
  if config.enabled and config.pointerSize == 64:
    return expr
  return "(" & expr & ") >>> 0"

# ─── String Interning ───

type
  InternCache* = object
    cache: Table[string, uint32]
    reverseCache: Table[uint32, string]
    nextIdx: uint32

proc newInternCache*(): InternCache =
  InternCache(
    cache: initTable[string, uint32](),
    reverseCache: initTable[uint32, string](),
    nextIdx: 1'u32,
  )

proc intern*(cache: var InternCache, str: string): uint32 =
  ## Cache a string and return its interned index.
  ## Avoids O(n) copy+encode per string sent to JS.
  if str in cache.cache:
    return cache.cache[str]
  let idx = cache.nextIdx
  cache.cache[str] = idx
  cache.reverseCache[idx] = str
  inc cache.nextIdx
  return idx

proc unintern*(cache: var InternCache, idx: uint32) =
  ## Remove a string from the intern cache.
  if idx in cache.reverseCache:
    let str = cache.reverseCache[idx]
    cache.cache.del(str)
    cache.reverseCache.del(idx)

proc clearInternCache*(cache: var InternCache) =
  ## Clear the entire intern cache.
  cache.cache.clear()
  cache.reverseCache.clear()
  cache.nextIdx = 1'u32

proc internLookup*(cache: InternCache, idx: uint32): string =
  ## Look up a string by its interned index.
  if idx in cache.reverseCache:
    return cache.reverseCache[idx]
  return ""

proc internCount*(cache: InternCache): int =
  ## Return the number of interned strings.
  return cache.cache.len

# ─── Additional CLI Flags ───

type
  CliFlags* = object
    demangle*: bool
    keepDebug*: bool
    removeNameSection*: bool
    removeProducersSection*: bool
    omitImports*: bool
    emitStart*: bool
    browser*: bool
    noModulesGlobal*: string
    omitDefaultModulePath*: bool
    splitLinkedModules*: bool

proc defaultCliFlags*(): CliFlags =
  CliFlags(
    demangle: false,
    keepDebug: false,
    removeNameSection: false,
    removeProducersSection: false,
    omitImports: false,
    emitStart: false,
    browser: false,
    noModulesGlobal: "wasm_bindgen",
    omitDefaultModulePath: false,
    splitLinkedModules: false,
  )

proc parseCliFlags*(args: seq[string]): CliFlags =
  ## Parse CLI flag arguments into a CliFlags object.
  result = defaultCliFlags()
  var i = 0
  while i < args.len:
    let arg = args[i]
    case arg
    of "--demangle":
      result.demangle = true
    of "--keep-debug":
      result.keepDebug = true
    of "--remove-name-section":
      result.removeNameSection = true
    of "--remove-producers-section":
      result.removeProducersSection = true
    of "--omit-imports":
      result.omitImports = true
    of "--emit-start":
      result.emitStart = true
    of "--browser":
      result.browser = true
    of "--no-modules-global":
      if i + 1 < args.len:
        inc i
        result.noModulesGlobal = args[i]
    of "--omit-default-module-path":
      result.omitDefaultModulePath = true
    of "--split-linked-modules":
      result.splitLinkedModules = true
    else:
      discard
    inc i

# ─── Wasm section constants ───

const
  SecCustom = 0
  SecStart = 8
  SecCode = 10

  ProducersSectionName = "producers"

# ─── Wasm section helpers ───

proc stripSection(wasmData: seq[byte], sectionId: byte): seq[byte] =
  ## Remove all instances of a section type from wasm binary.
  if wasmData.len < 8:
    return wasmData

  result = @[]
  result.add(wasmData[0..7]) # magic + version

  var pos = 8
  while pos < wasmData.len:
    let sid = wasmData[pos]
    inc pos

    let sizeStart = pos
    let size = int(readUleb128(wasmData, pos))
    let payloadStart = pos

    if sid == sectionId:
      pos = payloadStart + size
      continue

    result.add(sid)
    for i in sizeStart..<payloadStart:
      result.add(wasmData[i])
    for i in payloadStart..<(payloadStart + size):
      result.add(wasmData[i])
    pos = payloadStart + size

proc stripCustomSection(wasmData: seq[byte], name: string): seq[byte] =
  ## Remove a named custom section from wasm binary.
  if wasmData.len < 8:
    return wasmData

  result = @[]
  result.add(wasmData[0..7]) # magic + version

  var pos = 8
  while pos < wasmData.len:
    let sectionId = wasmData[pos]
    inc pos

    let sizeStart = pos
    let size = int(readUleb128(wasmData, pos))
    let payloadStart = pos

    if sectionId == 0:
      # Custom section — read name
      let nameLen = int(readUleb128(wasmData, pos))

      let nameBytes = wasmData[pos..<(pos + nameLen)]
      let sectionName = cast[string](nameBytes)

      if sectionName == name:
        pos = payloadStart + size
        continue

    # Keep this section
    result.add(sectionId)
    for i in sizeStart..<payloadStart:
      result.add(wasmData[i])
    for i in payloadStart..<(payloadStart + size):
      result.add(wasmData[i])
    pos = payloadStart + size

proc hasSection(wasmData: seq[byte], sectionId: byte): bool =
  var pos = 8
  while pos < wasmData.len:
    let sid = wasmData[pos]
    inc pos
    let size = int(readUleb128(wasmData, pos))
    if sid == sectionId:
      return true
    pos += size
  return false

proc injectStartSection(wasmData: seq[byte], startFuncIdx: uint32): seq[byte] =
  ## Inject a Start section into the wasm binary.
  if wasmData.len < 8:
    return wasmData

  result = @[]
  result.add(wasmData[0..7]) # magic + version

  var injected = false
  var pos = 8
  while pos < wasmData.len:
    let sectionId = wasmData[pos]
    inc pos

    let sizeStart = pos
    let size = int(readUleb128(wasmData, pos))
    let payloadStart = pos

    # Inject start section before Code section (id=10) or at end
    if not injected and sectionId >= SecCode:
      var payload: seq[byte] = @[]
      writeUleb128(payload, startFuncIdx)
      result.add(byte(SecStart))
      writeUleb128(result, uint32(payload.len))
      result.add(payload)
      injected = true

    # Copy original section
    result.add(sectionId)
    for i in sizeStart..<payloadStart:
      result.add(wasmData[i])
    for i in payloadStart..<(payloadStart + size):
      result.add(wasmData[i])
    pos = payloadStart + size

  if not injected:
    var payload: seq[byte] = @[]
    writeUleb128(payload, startFuncIdx)
    result.add(byte(SecStart))
    writeUleb128(result, uint32(payload.len))
    result.add(payload)

proc applyCliFlags*(wasmData: seq[byte], flags: CliFlags): seq[byte] =
  ## Apply CLI flags to wasm binary (strip sections, rename exports, etc.).
  result = wasmData

  if flags.removeNameSection:
    # The name section is a custom section with name "name"
    result = stripCustomSection(result, "name")

  if flags.removeProducersSection:
    result = stripCustomSection(result, "producers")

  if not flags.keepDebug:
    # Strip debug-related custom sections
    result = stripCustomSection(result, ".debug_info")
    result = stripCustomSection(result, ".debug_abbrev")
    result = stripCustomSection(result, ".debug_line")
    result = stripCustomSection(result, ".debug_str")
    result = stripCustomSection(result, ".debug_ranges")
    result = stripCustomSection(result, ".debug_loc")

  if flags.emitStart:
    if not hasSection(result, byte(SecStart)):
      result = injectStartSection(result, 0)

proc demangleNimName*(name: string): string =
  ## Attempt to demangle a Nim function name to a readable form.
  ## Nim mangled names follow patterns like: module__procName_XXXXX
  result = name
  let idx = result.find("__")
  if idx >= 0:
    result = result[idx + 2 .. ^1]
  # Strip trailing numeric suffix
  var endPos = result.len - 1
  while endPos > 0 and result[endPos] in Digits:
    dec endPos
  if endPos < result.len - 1 and endPos > 0:
    result = result[0 .. endPos]

when isMainModule:
  echo "emscripten module loaded"
  var cache = newInternCache()
  let idx1 = cache.intern("hello")
  let idx2 = cache.intern("world")
  let idx3 = cache.intern("hello")
  assert idx1 == idx3
  assert idx1 != idx2
  echo &"intern test passed: hello={idx1}, world={idx2}"
